# -*- coding: utf-8 -*-
"""AU_Workshop_mini_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13J3NmtNXAOPVD9c-OtX_cX9440HADqJr
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("rounakbanik/the-movies-dataset")

print("Path to dataset files:", path)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.preprocessing import StandardScaler

from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering

from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

movies = pd.read_csv('/kaggle/input/the-movies-dataset/movies_metadata.csv', low_memory=False)

ratings = pd.read_csv('/kaggle/input/the-movies-dataset/ratings_small.csv')

print(movies.shape)
print(ratings.shape)

movies.head()

movies = movies[['id','title','genres','popularity']]

movies = movies.dropna()

movies.head()

movies['id'] = pd.to_numeric(movies['id'], errors='coerce')

movies = movies.dropna()

movies.head()

ratings = ratings[['movieId','rating']]

avg_rating = ratings.groupby('movieId')['rating'].mean().reset_index()

avg_rating.columns = ['id','rating']

avg_rating.head()

movies = movies.merge(avg_rating, on='id', how='inner')

movies.head()

import ast

def extract_genres(text):
    genres = ast.literal_eval(text)
    return [g['name'] for g in genres]

movies['genres'] = movies['genres'].apply(extract_genres)

movies.head()

mlb = MultiLabelBinarizer()

genre_encoded = pd.DataFrame(
    mlb.fit_transform(movies['genres']),
    columns=mlb.classes_
)

genre_encoded.head()

features = pd.concat([
    genre_encoded,
    movies[['rating','popularity']].reset_index(drop=True)
], axis=1)

features.head()

scaler = StandardScaler()

X = scaler.fit_transform(features)

print(X.shape)

inertia = []

K = range(1,10)

for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(6,4))

plt.plot(K, inertia, marker='o')

plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("Inertia")

plt.show()

kmeans = KMeans(n_clusters=5, random_state=42)

movies['kmeans_cluster'] = kmeans.fit_predict(X)

movies[['title','rating','popularity','kmeans_cluster']].head()

hc = AgglomerativeClustering(n_clusters=5)

movies['hierarchical_cluster'] = hc.fit_predict(X)

movies[['title','hierarchical_cluster']].head()

pca = PCA(n_components=2)

pca_result = pca.fit_transform(X)

plt.figure(figsize=(8,6))

plt.scatter(
    pca_result[:,0],
    pca_result[:,1],
    c=movies['kmeans_cluster']
)

plt.title("Movie Clusters (PCA)")
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")

plt.show()

tsne = TSNE(n_components=2, random_state=42)

tsne_result = tsne.fit_transform(X)

plt.figure(figsize=(8,6))

plt.scatter(
    tsne_result[:,0],
    tsne_result[:,1],
    c=movies['kmeans_cluster']
)

plt.title("Movie Clusters (t-SNE)")

plt.show()

for i in range(5):

    print("\nCluster", i)

    print(movies[movies['kmeans_cluster']==i]['title'].head(10))

movies.to_csv("clustered_movies.csv", index=False)

movies.head()